Repository bakdata/streams-explorer, pull requests merged in 2021-04, with the labels that each got.

#79 Provide MetricProvider as a plugin
  README.md
  backend/streams_explorer/core/services/dataflow_graph.py
  backend/streams_explorer/default.py
  backend/streams_explorer/linker.py
  backend/streams_explorer/metric_provider.py
  backend/streams_explorer/streams_explorer.py
  backend/tests/test_dataflow_graph.py
  backend/tests/test_metricprovider.py
  backend/tests/test_streams_explorer.py
Labels: backend, enhancement

#83 Fix Kubernetes readiness probe
  helm-chart/index.yaml
  helm-chart/streams-explorer-0.1.0.tgz
  helm-chart/templates/deployment.yaml
Labels: bug

#84 Fix typing warnings
  backend/streams_explorer/core/k8s_app.py
  backend/streams_explorer/core/services/dataflow_graph.py
  backend/streams_explorer/core/services/metric_providers.py
  backend/streams_explorer/extractors.py
  backend/streams_explorer/py.typed
  backend/tests/test_metricprovider.py
Labels: enhancement

#85 Add support for StatefulSets
  backend/streams_explorer/core/k8s_app.py
  backend/streams_explorer/streams_explorer.py
  backend/tests/test_application.py
  backend/tests/test_k8s_app.py
  backend/tests/test_streams_explorer.py
  backend/tests/utils.py
  helm-chart/index.yaml
  helm-chart/streams-explorer-0.1.0.tgz
  helm-chart/templates/role.yaml
Labels: enhancement

#87 Minor chart additions (ingressClassName + imagePullSecrets)
  helm-chart/Chart.yaml
  helm-chart/index.yaml
  helm-chart/streams-explorer-0.1.1.tgz
  helm-chart/streams-explorer-0.1.2.tgz
  helm-chart/templates/deployment.yaml
  helm-chart/templates/ingress.yaml
  helm-chart/values.yaml
Labels: deployment

#90 Fix streams app classification false positives
  backend/streams_explorer/core/k8s_app.py
  backend/tests/test_k8s_app.py
  backend/tests/utils.py
Labels: bug
