Repository bakdata/streams-explorer, pull requests merged in 2021-02, with the labels that each got.

#36 Update graph automatically
  README.md
  backend/main.py
  backend/pyproject.toml
  backend/requirements.txt
  backend/settings.yaml
  backend/streams_explorer/core/config.py
  backend/streams_explorer/core/extractor/extractor_container.py
  backend/streams_explorer/default.py
  backend/streams_explorer/streams_explorer.py
  backend/tests/test_application.py
Labels: enhancement

#40 Add Grafana dashboards
  grafana/consumer-groups.json
  grafana/topics.json
Labels: documentation

#41 Link to consumer groups Grafana dashboard
  README.md
  backend/settings.yaml
  backend/streams_explorer/core/config.py
  backend/streams_explorer/defaultlinker.py
  backend/tests/test_linker.py
  backend/tests/test_streams_explorer.py
  backend/tests/utils.py
Labels: enhancement

#39 Migrate to Python 3 pathlib & minor cleanup
  backend/create_openapi_docs.py
  backend/streams_explorer/core/services/dataflow_graph.py
  backend/streams_explorer/core/services/linking_services.py
  backend/streams_explorer/models/graph.py
  backend/streams_explorer/plugins.py
  backend/tests/test_extractors.py
  backend/tests/test_linker.py
  frontend/src/api/fetchers.tsx
Labels: enhancement

#43 Add test for consumer group
  backend/tests/test_metricprovider.py
Labels: enhancement

#48 Fullscreen graph & handle window resizing
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/Details.tsx
  frontend/src/components/DetailsCard.tsx
  frontend/src/components/GraphVisualization.tsx
Labels: enhancement

#58 Add support for source connectors
  backend/streams_explorer/core/extractor/default/elasticsearch_sink.py
  backend/streams_explorer/core/extractor/default/jdbc_sink.py
  backend/streams_explorer/core/extractor/default/s3_sink.py
  backend/streams_explorer/core/extractor/extractor.py
  backend/streams_explorer/core/extractor/extractor_container.py
  backend/streams_explorer/core/services/dataflow_graph.py
  backend/streams_explorer/core/services/kafkaconnect.py
  backend/streams_explorer/core/services/metric_providers.py
  backend/streams_explorer/models/kafka_connector.py
  backend/streams_explorer/streams_explorer.py
  backend/tests/test_application.py
  backend/tests/test_dataflow_graph.py
  backend/tests/test_extractors.py
  backend/tests/test_node_info_extractor.py
  backend/tests/test_streams_explorer.py
Labels: enhancement

#60 Sanitize Kafka Connect config secrets
  backend/requirements.txt
  backend/streams_explorer/core/services/kafkaconnect.py
  backend/streams_explorer/streams_explorer.py
  backend/tests/test_kafka_connect.py
  backend/tests/test_streams_explorer.py
Labels: enhancement

#65 Fix generic extractors being loaded before plugins
  backend/streams_explorer/extractors.py
  backend/tests/test_application.py
  backend/tests/test_extractors.py
Labels: bug

#66 Display number of Connector tasks as metric
  backend/streams_explorer/core/services/metric_providers.py
  backend/streams_explorer/models/graph.py
  backend/tests/test_metricprovider.py
  backend/tests/test_metricprovider_data.py
  frontend/src/api/fetchers.tsx
  frontend/src/components/GraphVisualization.tsx
Labels: backend, enhancement, frontend

#67 Improvements to animated edges in graph
  frontend/src/components/GraphVisualization.test.tsx
  frontend/src/components/GraphVisualization.tsx
Labels: frontend

#68 Kubernetes health probes
  backend/streams_explorer/api/routes/api.py
  backend/streams_explorer/api/routes/kubernetes_health.py
  helm-chart/index.yaml
  helm-chart/streams-explorer-0.1.0.tgz
  helm-chart/templates/deployment.yaml
  helm-chart/values.yaml
Labels: backend

#63 Reduce Docker image size
  Dockerfile
Labels: enhancement

#71 Search and focus nodes
  frontend/src/App.tsx
  frontend/src/components/GraphVisualization.tsx
  frontend/src/graphConfiguration.ts
Labels: enhancement, frontend

#70 Update Readme
  README.md
  demo-atm-fraud/README.md
  screens/demo-pipeline.png
  screens/overview.png
  screens/streams-explorer.png
Labels: documentation
